### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlyBadawy** [TAj-src/BPQ_7plus#1]
Hello, Steve,,,
I have a question about this script please.. 
In the README, it says "To get the mail imported, make sure your script matches the BPQMail forward import file definition"...

Could you please elaborate more on this?

Thanks in advance,
73 de AL0Y

**Comment by TAj-src** [comment]
AL0Y,
In the scrips there are lines that need to be edited to get the directory paths correct.
e.g.
BASE_DIR="/home/<usr>/linbpq"
MAIL_DIR="$BASE_DIR/Mail"
OUT_DIR="$BASE_DIR/Mail/Export/7plus"
OUTPUT_FILE="$OUT_DIR/7plus.log"
LATEST_FILENAME="$BASE_DIR/latest_mailfile"

The need to all be configured as per your BPQ setup. And how your forward out the mail - e.g. 

OUT_DIR="$BASE_DIR/Mail/Export/7plus"

If your 7plus fwd script is not exporting to this directory, you need to change that.

Hope that helps
73 Steve

**Comment by TAj-src** [comment]
Information given. No more questions.
